# Generated by Django 4.1 on 2022-09-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='slug',
            field=models.SlugField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
