# Generated by Django 4.1 on 2022-09-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0003_remove_proyecto_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
