# Generated by Django 4.1 on 2022-09-06 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0004_proyecto_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='slug',
        ),
    ]
